### ISSUE TITLE
Overlap with datapackage-r

### ISSUE THREAD

**Issue by trallard** [annakrystalli/metadatar#1]
Hi!

I was wondering how much of an overlap this has with Frictionless data's datapackage-r [https://github.com/frictionlessdata/datapackage-r](https://github.com/frictionlessdata/datapackage-r)  
It might this package tackles some open issues on datapackage-r or the other way around. 
Also if this seems absolutely irrelevant feel free to ignore this issue

**Comment by annakrystalli** [comment]
Nice package! While it probably won't be of use here (not working with json), it may well be useful for [dataspice](https://github.com/ropenscilabs/dataspice)
